### ISSUE TITLE
crash: press back button to quit app cause crash

### ISSUE THREAD

**Issue by goodlg** [goodlg/V2EX-Android#4]
07-07 00:54:38.295  6999  6999 E AndroidRuntime: FATAL EXCEPTION: main
07-07 00:54:38.295  6999  6999 E AndroidRuntime: Process: test.demo.gyniu.v2ex, PID: 6999
07-07 00:54:38.295  6999  6999 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {test.demo.gyniu.v2ex/test.demo.gyniu.v2ex.Activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4240)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4258)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.app.ActivityThread.-wrap6(ActivityThread.java)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at test.demo.gyniu.v2ex.adapter.AllNodesAdapter.setDataSource(AllNodesAdapter.java:89)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at test.demo.gyniu.v2ex.fragment.NodeListFragment.onLoaderReset(NodeListFragment.java:151)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.destroy(LoaderManager.java:357)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.support.v4.app.LoaderManagerImpl.doDestroy(LoaderManager.java:827)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.support.v4.app.Fragment.onDestroy(Fragment.java:1389)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.support.v4.app.Fragment.performDestroy(Fragment.java:2202)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1196)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2083)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:244)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:368)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:203)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at test.demo.gyniu.v2ex.Activity.MainActivity.onDestroy(MainActivity.java:179)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:6886)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
07-07 00:54:38.295  6999  6999 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4227)

**Comment by goodlg** [comment]
it should be close according to last comment
